import {
  map,
} from 'rxjs/operators';
import { BehaviorSubject } from 'rxjs';
import MetaList from './MetaList';
import Meta from './Meta';

/**
 * This decorates and expands a value (standard) Subject
 * into a subject of errors generated by its value.
 * It tracks the last non-errored value,
 * the errors of the current value,
 * and the last valid value (considered the current value).
 *
 */
export default class FilteredSubject {
  constructor(initialValue = null, filters) {
    this._initBase(initialValue);
    this._initMeta(initialValue, filters);
    this._initSubject();
  }

  get meta() {
    return this._metaList.annotate(this.value);
  }

  _initMeta(initialValue, filters) {
    this._metaList = new MetaList(filters);
    this.lastValid = this._metaList.annotate(initialValue, this).length ? undefined : initialValue;
  }

  _initSubject() {
    this._subject = this._base.pipe(
      map((value) => {
        const meta = this._metaList.annotate(value, this);
        if (!meta.length) {
          this.lastValid = value;
        }
        return { value, meta, lastValid: this.lastValid };
      }),
    );
  }

  _initBase(initialValue) {
    this.value = initialValue;
    this._base = new BehaviorSubject(initialValue);
    this._base.subscribe((v) => this.value = v);
  }

  addMeta(test, name = '', order = 1) {
    this._metaList.add(new Meta(test, name, order));
  }

  get subject() {
    return this._subject;
  }

  subscribe(...methods) {
    this._subject.subscribe(...methods);
  }

  next(value) {
    this._base.next(value);
  }

  complete() {
    this._base.complete();
  }
}
